/**
 * Even Fibonacci numbers
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms
 * will be:
 *
 *                                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * Created by doruk on 31.05.2017.
 */

public class Main {

    private static final int LIMIT = 4000000;

    public static void main(String[] args) {
        System.out.print(sumOfEvenFibonacciNumbers(2, 1));
    }

    private static int sumOfEvenFibonacciNumbers(int firstNum, int secondNum){
        if(firstNum < LIMIT){
            if ((firstNum + secondNum)%2 == 0){
                return (firstNum + secondNum) + sumOfEvenFibonacciNumbers(firstNum + secondNum, firstNum);
            } else {
                return sumOfEvenFibonacciNumbers(firstNum + secondNum, firstNum);
            }
        }else {
            return 2;
        }
    }

}
