import java.util.ArrayList;

/**
 * Pentagon numbers
 * Problem 44
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 *
 *                               1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is
 * minimised; what is the value of D?
 *
 * Created by doruk on 3.06.2017.
 */

public class Main {

    public static void main(String[] args) {

        long pentagonalNumberExtract = 0;
        for (int i = 1; i < 10000; i++){
            long firstNumber = (i * ((3 * i) - 1))/ 2;
            for (int j = i + 1; j < 10000; j++){
                long secondNumber = (j * ((3 * j) - 1))/ 2;

                if (isPentagonal(secondNumber - firstNumber) && isPentagonal(secondNumber + firstNumber)){
                    pentagonalNumberExtract = secondNumber - firstNumber;
                }
            }
        }

        System.out.print(pentagonalNumberExtract);
    }

    private static boolean isPentagonal(long number) {
        double pentagonal = (Math.sqrt(1 + 24 * number) + 1.0) / 6.0;
        return pentagonal == ((int)pentagonal);
    }
}
